name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */8 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2.0.0-rc.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg
